import Wrapper from "@/components/Wrapper";
import OrderCard from "@/components/Orders/OrderCard";
import OrdersModal from "@/components/Modal/OrdersModal";
import { useState } from "react";

const OrderHistory = () => {
  const [showOrdersModal, setShowOrdersModal] = useState({
    show: false,
    productId: 0,
    productIndex: -1,
  });
  const currentOrder = [
    {
      quantity: 4,
      productId: 1,
      selectedSize: 1.7,
      selectedFlavour: "Mocha Cappuccino",
      id: 1,
      name: "ON (Optimum Nutrition) Gold Standard 100% Whey Protein",
      price: 3099,
      description:
        "Gold Standard 100% Whey Blend - 24g blended protein consisting of whey protein isolate, whey protein concentrate, and whey peptides/hydrolysates to support muscle recovery. Primary protein source is Isolate, they don't call it the Gold Standard of quality for nothing.\n\nWhat Does It Have -11 grams of naturally occurring EAAs, including 5.5 grams of naturally occurring BCAAs, and over 4 grams of naturally occurring Glutamine and Glutamic Acid in each serving to support endurance and muscle recovery. Gluten-Free & suitable for Vegetarians\n\nSMS ON <space> 6 digit unique code on the pack to 57575 or visit our website Authenticateon.in to instantly check the authenticity of the product\n\nCountry of Origin: India, it is manufactured in India, in a facility that is ISO 14001 & 22000 certified and Inspected & Approved by Food Safety Standard Authority of India. Whey Imported from Europe. Manufactured for OPTIMUM NUTRITION, INC. By Tirupati Wellness Pvt Ltd, Surajpur, Nahan Road, Paonta Sahib Dist. Sirmour- 173025 (HP)\n",
      sizes: [
        {
          mrp: 3899,
          size: "0.910",
          price: 3099,
          stock: "TRUE",
          flavour: "Double Rich Chocolate",
        },
        {
          mrp: 3899,
          size: "0.910",
          price: 3099,
          stock: "TRUE",
          flavour: "Cookies & Cream",
        },
        {
          mrp: 3899,
          size: "0.910",
          price: 3099,
          stock: "TRUE",
          flavour: "Mocha Cappuccino",
        },
        {
          mrp: 6599,
          size: "1.7",
          price: 4699,
          stock: "TRUE",
          flavour: "Double Rich Chocolate",
        },
        {
          mrp: 6599,
          size: "1.7",
          price: 4699,
          stock: "TRUE",
          flavour: "Cookies & Cream",
        },
        {
          mrp: 6599,
          size: "1.7",
          price: 4699,
          stock: "TRUE",
          flavour: "Mocha Cappuccino",
        },
        {
          size: "0.910",
          stock: "FALSE",
          flavour: "Vanilla Ice Cream",
        },
      ],
      mrp: 3899,
      slug: "on-optimum-nutrition-gold-standard-100-whey-protein",
      brand: "Optimum Nutrition",
      size: 0.91,
      sizeUnit: "kg",
      hasFlavour: true,
      createdAt: "2024-03-23T14:27:10.620Z",
      updatedAt: "2024-03-23T17:30:55.400Z",
      publishedAt: "2024-03-23T14:27:19.730Z",
      thumbnail: {
        id: 5,
        name: "optimum.jpg",
        alternativeText: null,
        caption: null,
        width: 1000,
        height: 1000,
        formats: {
          small: {
            ext: ".jpg",
            url: "https://res.cloudinary.com/dybxysxcl/image/upload/v1711203967/small_optimum_971a42c68c.jpg",
            hash: "small_optimum_971a42c68c",
            mime: "image/jpeg",
            name: "small_optimum.jpg",
            path: null,
            size: 32.84,
            width: 500,
            height: 500,
            provider_metadata: {
              public_id: "small_optimum_971a42c68c",
              resource_type: "image",
            },
          },
          medium: {
            ext: ".jpg",
            url: "https://res.cloudinary.com/dybxysxcl/image/upload/v1711203967/medium_optimum_971a42c68c.jpg",
            hash: "medium_optimum_971a42c68c",
            mime: "image/jpeg",
            name: "medium_optimum.jpg",
            path: null,
            size: 63.46,
            width: 750,
            height: 750,
            provider_metadata: {
              public_id: "medium_optimum_971a42c68c",
              resource_type: "image",
            },
          },
          thumbnail: {
            ext: ".jpg",
            url: "https://res.cloudinary.com/dybxysxcl/image/upload/v1711203966/thumbnail_optimum_971a42c68c.jpg",
            hash: "thumbnail_optimum_971a42c68c",
            mime: "image/jpeg",
            name: "thumbnail_optimum.jpg",
            path: null,
            size: 4.91,
            width: 156,
            height: 156,
            provider_metadata: {
              public_id: "thumbnail_optimum_971a42c68c",
              resource_type: "image",
            },
          },
        },
        hash: "optimum_971a42c68c",
        ext: ".jpg",
        mime: "image/jpeg",
        size: 63.08,
        url: "https://res.cloudinary.com/dybxysxcl/image/upload/v1711203968/optimum_971a42c68c.jpg",
        previewUrl: null,
        provider: "cloudinary",
        provider_metadata: {
          public_id: "optimum_971a42c68c",
          resource_type: "image",
        },
        createdAt: "2024-03-23T14:26:08.180Z",
        updatedAt: "2024-03-23T14:26:08.180Z",
      },
      cartItems: [
        {
          quantity: 4,
          productId: 1,
          selectedSize: 1.7,
          selectedFlavour: "Mocha Cappuccino",
        },
        {
          quantity: 2,
          productId: 1,
          selectedSize: 0.91,
          selectedFlavour: "Cookies & Cream",
        },
      ],
      cartProducts: [
        {
          id: 1,
          name: "ON (Optimum Nutrition) Gold Standard 100% Whey Protein",
          price: 3099,
          description:
            "Gold Standard 100% Whey Blend - 24g blended protein consisting of whey protein isolate, whey protein concentrate, and whey peptides/hydrolysates to support muscle recovery. Primary protein source is Isolate, they don't call it the Gold Standard of quality for nothing.\n\nWhat Does It Have -11 grams of naturally occurring EAAs, including 5.5 grams of naturally occurring BCAAs, and over 4 grams of naturally occurring Glutamine and Glutamic Acid in each serving to support endurance and muscle recovery. Gluten-Free & suitable for Vegetarians\n\nSMS ON <space> 6 digit unique code on the pack to 57575 or visit our website Authenticateon.in to instantly check the authenticity of the product\n\nCountry of Origin: India, it is manufactured in India, in a facility that is ISO 14001 & 22000 certified and Inspected & Approved by Food Safety Standard Authority of India. Whey Imported from Europe. Manufactured for OPTIMUM NUTRITION, INC. By Tirupati Wellness Pvt Ltd, Surajpur, Nahan Road, Paonta Sahib Dist. Sirmour- 173025 (HP)\n",
          sizes: [
            {
              mrp: 3899,
              size: "0.910",
              price: 3099,
              stock: "TRUE",
              flavour: "Double Rich Chocolate",
            },
            {
              mrp: 3899,
              size: "0.910",
              price: 3099,
              stock: "TRUE",
              flavour: "Cookies & Cream",
            },
            {
              mrp: 3899,
              size: "0.910",
              price: 3099,
              stock: "TRUE",
              flavour: "Mocha Cappuccino",
            },
            {
              mrp: 6599,
              size: "1.7",
              price: 4699,
              stock: "TRUE",
              flavour: "Double Rich Chocolate",
            },
            {
              mrp: 6599,
              size: "1.7",
              price: 4699,
              stock: "TRUE",
              flavour: "Cookies & Cream",
            },
            {
              mrp: 6599,
              size: "1.7",
              price: 4699,
              stock: "TRUE",
              flavour: "Mocha Cappuccino",
            },
            {
              size: "0.910",
              stock: "FALSE",
              flavour: "Vanilla Ice Cream",
            },
          ],
          mrp: 3899,
          slug: "on-optimum-nutrition-gold-standard-100-whey-protein",
          brand: "Optimum Nutrition",
          size: 0.91,
          sizeUnit: "kg",
          hasFlavour: true,
          createdAt: "2024-03-23T14:27:10.620Z",
          updatedAt: "2024-03-23T17:30:55.400Z",
          publishedAt: "2024-03-23T14:27:19.730Z",
          thumbnail: {
            id: 5,
            name: "optimum.jpg",
            alternativeText: null,
            caption: null,
            width: 1000,
            height: 1000,
            formats: {
              small: {
                ext: ".jpg",
                url: "https://res.cloudinary.com/dybxysxcl/image/upload/v1711203967/small_optimum_971a42c68c.jpg",
                hash: "small_optimum_971a42c68c",
                mime: "image/jpeg",
                name: "small_optimum.jpg",
                path: null,
                size: 32.84,
                width: 500,
                height: 500,
                provider_metadata: {
                  public_id: "small_optimum_971a42c68c",
                  resource_type: "image",
                },
              },
              medium: {
                ext: ".jpg",
                url: "https://res.cloudinary.com/dybxysxcl/image/upload/v1711203967/medium_optimum_971a42c68c.jpg",
                hash: "medium_optimum_971a42c68c",
                mime: "image/jpeg",
                name: "medium_optimum.jpg",
                path: null,
                size: 63.46,
                width: 750,
                height: 750,
                provider_metadata: {
                  public_id: "medium_optimum_971a42c68c",
                  resource_type: "image",
                },
              },
              thumbnail: {
                ext: ".jpg",
                url: "https://res.cloudinary.com/dybxysxcl/image/upload/v1711203966/thumbnail_optimum_971a42c68c.jpg",
                hash: "thumbnail_optimum_971a42c68c",
                mime: "image/jpeg",
                name: "thumbnail_optimum.jpg",
                path: null,
                size: 4.91,
                width: 156,
                height: 156,
                provider_metadata: {
                  public_id: "thumbnail_optimum_971a42c68c",
                  resource_type: "image",
                },
              },
            },
            hash: "optimum_971a42c68c",
            ext: ".jpg",
            mime: "image/jpeg",
            size: 63.08,
            url: "https://res.cloudinary.com/dybxysxcl/image/upload/v1711203968/optimum_971a42c68c.jpg",
            previewUrl: null,
            provider: "cloudinary",
            provider_metadata: {
              public_id: "optimum_971a42c68c",
              resource_type: "image",
            },
            createdAt: "2024-03-23T14:26:08.180Z",
            updatedAt: "2024-03-23T14:26:08.180Z",
          },
        },
      ],
      address: {
        id: 0.39329162132987294,
        city: "JAIPUR",
        name: "Tajender Batra",
        type: "work",
        state: "RJ",
        mobile: "9116511522",
        address: "Navi Mumbai",
        pincode: "400705",
      },
      paymentMethod: "Pay On Delivery",
    },
    {
      quantity: 2,
      productId: 1,
      selectedSize: 0.91,
      selectedFlavour: "Cookies & Cream",
      id: 1,
      name: "ON (Optimum Nutrition) Gold Standard 100% Whey Protein",
      price: 3099,
      description:
        "Gold Standard 100% Whey Blend - 24g blended protein consisting of whey protein isolate, whey protein concentrate, and whey peptides/hydrolysates to support muscle recovery. Primary protein source is Isolate, they don't call it the Gold Standard of quality for nothing.\n\nWhat Does It Have -11 grams of naturally occurring EAAs, including 5.5 grams of naturally occurring BCAAs, and over 4 grams of naturally occurring Glutamine and Glutamic Acid in each serving to support endurance and muscle recovery. Gluten-Free & suitable for Vegetarians\n\nSMS ON <space> 6 digit unique code on the pack to 57575 or visit our website Authenticateon.in to instantly check the authenticity of the product\n\nCountry of Origin: India, it is manufactured in India, in a facility that is ISO 14001 & 22000 certified and Inspected & Approved by Food Safety Standard Authority of India. Whey Imported from Europe. Manufactured for OPTIMUM NUTRITION, INC. By Tirupati Wellness Pvt Ltd, Surajpur, Nahan Road, Paonta Sahib Dist. Sirmour- 173025 (HP)\n",
      sizes: [
        {
          mrp: 3899,
          size: "0.910",
          price: 3099,
          stock: "TRUE",
          flavour: "Double Rich Chocolate",
        },
        {
          mrp: 3899,
          size: "0.910",
          price: 3099,
          stock: "TRUE",
          flavour: "Cookies & Cream",
        },
        {
          mrp: 3899,
          size: "0.910",
          price: 3099,
          stock: "TRUE",
          flavour: "Mocha Cappuccino",
        },
        {
          mrp: 6599,
          size: "1.7",
          price: 4699,
          stock: "TRUE",
          flavour: "Double Rich Chocolate",
        },
        {
          mrp: 6599,
          size: "1.7",
          price: 4699,
          stock: "TRUE",
          flavour: "Cookies & Cream",
        },
        {
          mrp: 6599,
          size: "1.7",
          price: 4699,
          stock: "TRUE",
          flavour: "Mocha Cappuccino",
        },
        {
          size: "0.910",
          stock: "FALSE",
          flavour: "Vanilla Ice Cream",
        },
      ],
      mrp: 3899,
      slug: "on-optimum-nutrition-gold-standard-100-whey-protein",
      brand: "Optimum Nutrition",
      size: 0.91,
      sizeUnit: "kg",
      hasFlavour: true,
      createdAt: "2024-03-23T14:27:10.620Z",
      updatedAt: "2024-03-23T17:30:55.400Z",
      publishedAt: "2024-03-23T14:27:19.730Z",
      thumbnail: {
        id: 5,
        name: "optimum.jpg",
        alternativeText: null,
        caption: null,
        width: 1000,
        height: 1000,
        formats: {
          small: {
            ext: ".jpg",
            url: "https://res.cloudinary.com/dybxysxcl/image/upload/v1711203967/small_optimum_971a42c68c.jpg",
            hash: "small_optimum_971a42c68c",
            mime: "image/jpeg",
            name: "small_optimum.jpg",
            path: null,
            size: 32.84,
            width: 500,
            height: 500,
            provider_metadata: {
              public_id: "small_optimum_971a42c68c",
              resource_type: "image",
            },
          },
          medium: {
            ext: ".jpg",
            url: "https://res.cloudinary.com/dybxysxcl/image/upload/v1711203967/medium_optimum_971a42c68c.jpg",
            hash: "medium_optimum_971a42c68c",
            mime: "image/jpeg",
            name: "medium_optimum.jpg",
            path: null,
            size: 63.46,
            width: 750,
            height: 750,
            provider_metadata: {
              public_id: "medium_optimum_971a42c68c",
              resource_type: "image",
            },
          },
          thumbnail: {
            ext: ".jpg",
            url: "https://res.cloudinary.com/dybxysxcl/image/upload/v1711203966/thumbnail_optimum_971a42c68c.jpg",
            hash: "thumbnail_optimum_971a42c68c",
            mime: "image/jpeg",
            name: "thumbnail_optimum.jpg",
            path: null,
            size: 4.91,
            width: 156,
            height: 156,
            provider_metadata: {
              public_id: "thumbnail_optimum_971a42c68c",
              resource_type: "image",
            },
          },
        },
        hash: "optimum_971a42c68c",
        ext: ".jpg",
        mime: "image/jpeg",
        size: 63.08,
        url: "https://res.cloudinary.com/dybxysxcl/image/upload/v1711203968/optimum_971a42c68c.jpg",
        previewUrl: null,
        provider: "cloudinary",
        provider_metadata: {
          public_id: "optimum_971a42c68c",
          resource_type: "image",
        },
        createdAt: "2024-03-23T14:26:08.180Z",
        updatedAt: "2024-03-23T14:26:08.180Z",
      },
      cartItems: [
        {
          quantity: 4,
          productId: 1,
          selectedSize: 1.7,
          selectedFlavour: "Mocha Cappuccino",
        },
        {
          quantity: 2,
          productId: 1,
          selectedSize: 0.91,
          selectedFlavour: "Cookies & Cream",
        },
      ],
      cartProducts: [
        {
          id: 1,
          name: "ON (Optimum Nutrition) Gold Standard 100% Whey Protein",
          price: 3099,
          description:
            "Gold Standard 100% Whey Blend - 24g blended protein consisting of whey protein isolate, whey protein concentrate, and whey peptides/hydrolysates to support muscle recovery. Primary protein source is Isolate, they don't call it the Gold Standard of quality for nothing.\n\nWhat Does It Have -11 grams of naturally occurring EAAs, including 5.5 grams of naturally occurring BCAAs, and over 4 grams of naturally occurring Glutamine and Glutamic Acid in each serving to support endurance and muscle recovery. Gluten-Free & suitable for Vegetarians\n\nSMS ON <space> 6 digit unique code on the pack to 57575 or visit our website Authenticateon.in to instantly check the authenticity of the product\n\nCountry of Origin: India, it is manufactured in India, in a facility that is ISO 14001 & 22000 certified and Inspected & Approved by Food Safety Standard Authority of India. Whey Imported from Europe. Manufactured for OPTIMUM NUTRITION, INC. By Tirupati Wellness Pvt Ltd, Surajpur, Nahan Road, Paonta Sahib Dist. Sirmour- 173025 (HP)\n",
          sizes: [
            {
              mrp: 3899,
              size: "0.910",
              price: 3099,
              stock: "TRUE",
              flavour: "Double Rich Chocolate",
            },
            {
              mrp: 3899,
              size: "0.910",
              price: 3099,
              stock: "TRUE",
              flavour: "Cookies & Cream",
            },
            {
              mrp: 3899,
              size: "0.910",
              price: 3099,
              stock: "TRUE",
              flavour: "Mocha Cappuccino",
            },
            {
              mrp: 6599,
              size: "1.7",
              price: 4699,
              stock: "TRUE",
              flavour: "Double Rich Chocolate",
            },
            {
              mrp: 6599,
              size: "1.7",
              price: 4699,
              stock: "TRUE",
              flavour: "Cookies & Cream",
            },
            {
              mrp: 6599,
              size: "1.7",
              price: 4699,
              stock: "TRUE",
              flavour: "Mocha Cappuccino",
            },
            {
              size: "0.910",
              stock: "FALSE",
              flavour: "Vanilla Ice Cream",
            },
          ],
          mrp: 3899,
          slug: "on-optimum-nutrition-gold-standard-100-whey-protein",
          brand: "Optimum Nutrition",
          size: 0.91,
          sizeUnit: "kg",
          hasFlavour: true,
          createdAt: "2024-03-23T14:27:10.620Z",
          updatedAt: "2024-03-23T17:30:55.400Z",
          publishedAt: "2024-03-23T14:27:19.730Z",
          thumbnail: {
            id: 5,
            name: "optimum.jpg",
            alternativeText: null,
            caption: null,
            width: 1000,
            height: 1000,
            formats: {
              small: {
                ext: ".jpg",
                url: "https://res.cloudinary.com/dybxysxcl/image/upload/v1711203967/small_optimum_971a42c68c.jpg",
                hash: "small_optimum_971a42c68c",
                mime: "image/jpeg",
                name: "small_optimum.jpg",
                path: null,
                size: 32.84,
                width: 500,
                height: 500,
                provider_metadata: {
                  public_id: "small_optimum_971a42c68c",
                  resource_type: "image",
                },
              },
              medium: {
                ext: ".jpg",
                url: "https://res.cloudinary.com/dybxysxcl/image/upload/v1711203967/medium_optimum_971a42c68c.jpg",
                hash: "medium_optimum_971a42c68c",
                mime: "image/jpeg",
                name: "medium_optimum.jpg",
                path: null,
                size: 63.46,
                width: 750,
                height: 750,
                provider_metadata: {
                  public_id: "medium_optimum_971a42c68c",
                  resource_type: "image",
                },
              },
              thumbnail: {
                ext: ".jpg",
                url: "https://res.cloudinary.com/dybxysxcl/image/upload/v1711203966/thumbnail_optimum_971a42c68c.jpg",
                hash: "thumbnail_optimum_971a42c68c",
                mime: "image/jpeg",
                name: "thumbnail_optimum.jpg",
                path: null,
                size: 4.91,
                width: 156,
                height: 156,
                provider_metadata: {
                  public_id: "thumbnail_optimum_971a42c68c",
                  resource_type: "image",
                },
              },
            },
            hash: "optimum_971a42c68c",
            ext: ".jpg",
            mime: "image/jpeg",
            size: 63.08,
            url: "https://res.cloudinary.com/dybxysxcl/image/upload/v1711203968/optimum_971a42c68c.jpg",
            previewUrl: null,
            provider: "cloudinary",
            provider_metadata: {
              public_id: "optimum_971a42c68c",
              resource_type: "image",
            },
            createdAt: "2024-03-23T14:26:08.180Z",
            updatedAt: "2024-03-23T14:26:08.180Z",
          },
        },
      ],
      address: {
        id: 0.39329162132987294,
        city: "JAIPUR",
        name: "Tajender Batra",
        type: "work",
        state: "RJ",
        mobile: "9116511522",
        address: "Navi Mumbai",
        pincode: "400705",
      },
      paymentMethod: "Pay On Delivery",
    },
  ];
  return (
    <>
      <Wrapper className="mt-5">
        {currentOrder?.map((order, index) => (
          <OrderCard
            orderDetails={order}
            setShowOrdersModal={setShowOrdersModal}
            key={index}
            orderIndex={index}
          />
        ))}
      </Wrapper>
      {showOrdersModal.show ? (
        <OrdersModal
          orderDetails={currentOrder}
          showOrdersModal={showOrdersModal}
          setShowModal={setShowOrdersModal}
        />
      ) : (
        <></>
      )}
    </>
  );
};

export default OrderHistory;
